### ISSUE TITLE
Image Factory Pull Fails for v1.7.5 but Works for 1.7.4

### ISSUE THREAD

**Issue by no1here0003** [siderolabs/image-factory#125] opened 2024-06-23 03:56 UTC
Hello!

I'm able to create images via the UI, however I'm unable to pull the images I have used for 1.7.4:

Here's v1.7.5:
```
> docker pull factory.talos.dev/installer/d0c3e835853d22377d0bb370d2058854b56c942fe0f9ee33d988b737c1842d90:v1.7.5
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```

Here's v1.7.4:

```
> docker pull factory.talos.dev/installer/d0c3e835853d22377d0bb370d2058854b56c942fe0f9ee33d988b737c1842d90:v1.7.4
v1.7.4: Pulling from installer/d0c3e835853d22377d0bb370d2058854b56c942fe0f9ee33d988b737c1842d90
42b9d8426a4a: Pull complete
5f586388d5a6: Pull complete
Digest: sha256:7017359d0d83202502e61ba7fb0385cff359458034836e54f8dfdc9af434fa03
Status: Downloaded newer image for factory.talos.dev/installer/d0c3e835853d22377d0bb370d2058854b56c942fe0f9ee33d988b737c1842d90:v1.7.4
factory.talos.dev/installer/d0c3e835853d22377d0bb370d2058854b56c942fe0f9ee33d988b737c1842d90:v1.7.4
```

**Comment by frezbo** [comment] 2024-06-23 05:40
Fixed now, duplicate of #124

**Closed by frezbo** 2024-06-23 05:40 UTC
